apiVersion: v1
kind: Pod
metadata:
  name: ssh-pod
spec:
  containers:
  - name: sshd
    image: ubuntu:20.04
    ports:
    - containerPort: 22
    volumeMounts:
    - name: ssh-key-volume
      mountPath: /root/.ssh
    securityContext:
      privileged: true
    command: ["/bin/sh", "-c"]
    args:
    - |
      apt-get update &&
      apt-get install -y openssh-server &&
      echo "root:root" | chpasswd &&
      service ssh start &&
      tail -f /dev/null
  volumes:
  - name: config-volume
    secret:
      secretName: sshdhelper-key-secret
      items:
      - key: ssh-publickey
        path: authorized_keys
  - name: ssh-key-volume
    emptyDir: {}
  initContainers:
  - name: ssh-key-dir
    image: alpine:3.13
    command:
    - /bin/sh
    - -c
    - |
      cp /root/config-volume/authorized_keys /root/ssh-key-volume/ &&
      chmod 700 /root/ssh-key-volume/ &&
      chmod 600 /root/ssh-key-volume/authorized_keys
    volumeMounts:
    - name: config-volume
      mountPath: /root/config-volume
    - name: ssh-key-volume
      mountPath: /root/ssh-key-volume
